// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SantiyeOnMuh.DataAccess.Concrete;

#nullable disable

namespace SantiyeOnMuh.DataAccess.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20230301125813_mig5")]
    partial class mig5
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SantiyeOnMuh.Entity.BankaHesap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BankaAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Durum")
                        .HasColumnType("bit");

                    b.Property<string>("HesapAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HesapNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IbanNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BankaHesaps");
                });

            modelBuilder.Entity("SantiyeOnMuh.Entity.BankaKasa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BankaHesapId")
                        .HasColumnType("int");

                    b.Property<int?>("CekKaynak")
                        .HasColumnType("int");

                    b.Property<decimal>("Cikan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Durum")
                        .HasColumnType("bit");

                    b.Property<decimal>("Giren")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("NakitKaynak")
                        .HasColumnType("int");

                    b.Property<string>("Nitelik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SantiyeKasaKaynak")
                        .HasColumnType("int");

                    b.Property<DateTime>("SistemeGiris")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SonGuncelleme")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BankaHesapId");

                    b.ToTable("BankaKasas");
                });

            modelBuilder.Entity("SantiyeOnMuh.Entity.CariGiderKalemi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Durum")
                        .HasColumnType("bit");

                    b.Property<bool>("Tur")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("CariGiderKalemis");
                });

            modelBuilder.Entity("SantiyeOnMuh.Entity.CariHesap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Durum")
                        .HasColumnType("bit");

                    b.Property<string>("IlgiliKisi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IlgiliKisiTelefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Odeme")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SantiyeId")
                        .HasColumnType("int");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VergiNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SantiyeId");

                    b.ToTable("CariHesaps");
                });

            modelBuilder.Entity("SantiyeOnMuh.Entity.CariKasa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Alacak")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BirimFiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Borc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CariGiderKalemiId")
                        .HasColumnType("int");

                    b.Property<int>("CariHesapId")
                        .HasColumnType("int");

                    b.Property<int?>("CekKaynak")
                        .HasColumnType("int");

                    b.Property<bool>("Durum")
                        .HasColumnType("bit");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Miktar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("NakitKaynak")
                        .HasColumnType("int");

                    b.Property<DateTime>("SistemeGiris")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SonGuncelleme")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CariGiderKalemiId");

                    b.HasIndex("CariHesapId");

                    b.ToTable("CariKasas");
                });

            modelBuilder.Entity("SantiyeOnMuh.Entity.Cek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BankaHesapId")
                        .HasColumnType("int");

                    b.Property<int?>("BankaKasaKaynak")
                        .HasColumnType("int");

                    b.Property<int>("CariHesapId")
                        .HasColumnType("int");

                    b.Property<int?>("CariKasaKaynak")
                        .HasColumnType("int");

                    b.Property<string>("CekNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Durum")
                        .HasColumnType("bit");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("OdemeDurumu")
                        .HasColumnType("bit");

                    b.Property<int>("SirketId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SistemeGiris")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SonGuncelleme")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BankaHesapId");

                    b.HasIndex("CariHesapId");

                    b.HasIndex("SirketId");

                    b.ToTable("Ceks");
                });

            modelBuilder.Entity("SantiyeOnMuh.Entity.Nakit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BankaHesapId")
                        .HasColumnType("int");

                    b.Property<int?>("BankaKasaKaynak")
                        .HasColumnType("int");

                    b.Property<int>("CariHesapId")
                        .HasColumnType("int");

                    b.Property<int?>("CariKasaKaynak")
                        .HasColumnType("int");

                    b.Property<bool>("Durum")
                        .HasColumnType("bit");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SirketId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SistemeGiris")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SonGuncelleme")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BankaHesapId");

                    b.HasIndex("CariHesapId");

                    b.HasIndex("SirketId");

                    b.ToTable("Nakits");
                });

            modelBuilder.Entity("SantiyeOnMuh.Entity.Santiye", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Durum")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Santiyes");
                });

            modelBuilder.Entity("SantiyeOnMuh.Entity.SantiyeGiderKalemi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Durum")
                        .HasColumnType("bit");

                    b.Property<bool>("Tur")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("SantiyeGiderKalemis");
                });

            modelBuilder.Entity("SantiyeOnMuh.Entity.SantiyeKasa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BankaKasaKaynak")
                        .HasColumnType("int");

                    b.Property<bool>("Durum")
                        .HasColumnType("bit");

                    b.Property<decimal>("Gelir")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Gider")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kisi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("No")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SantiyeGiderKalemiId")
                        .HasColumnType("int");

                    b.Property<int>("SantiyeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SistemeGiris")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SonGuncelleme")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SantiyeGiderKalemiId");

                    b.HasIndex("SantiyeId");

                    b.ToTable("SantiyesKasas");
                });

            modelBuilder.Entity("SantiyeOnMuh.Entity.Sirket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Durum")
                        .HasColumnType("bit");

                    b.Property<string>("VergiNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sirkets");
                });

            modelBuilder.Entity("SantiyeOnMuh.Entity.BankaKasa", b =>
                {
                    b.HasOne("SantiyeOnMuh.Entity.BankaHesap", "BankaHesap")
                        .WithMany("BankaKasas")
                        .HasForeignKey("BankaHesapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BankaHesap");
                });

            modelBuilder.Entity("SantiyeOnMuh.Entity.CariHesap", b =>
                {
                    b.HasOne("SantiyeOnMuh.Entity.Santiye", "Santiye")
                        .WithMany("CariHesaps")
                        .HasForeignKey("SantiyeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Santiye");
                });

            modelBuilder.Entity("SantiyeOnMuh.Entity.CariKasa", b =>
                {
                    b.HasOne("SantiyeOnMuh.Entity.CariGiderKalemi", "CariGiderKalemi")
                        .WithMany("CariKasas")
                        .HasForeignKey("CariGiderKalemiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SantiyeOnMuh.Entity.CariHesap", "CariHesap")
                        .WithMany("CariKasas")
                        .HasForeignKey("CariHesapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CariGiderKalemi");

                    b.Navigation("CariHesap");
                });

            modelBuilder.Entity("SantiyeOnMuh.Entity.Cek", b =>
                {
                    b.HasOne("SantiyeOnMuh.Entity.BankaHesap", "BankaHesap")
                        .WithMany("Ceks")
                        .HasForeignKey("BankaHesapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SantiyeOnMuh.Entity.CariHesap", "CariHesap")
                        .WithMany("Ceks")
                        .HasForeignKey("CariHesapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SantiyeOnMuh.Entity.Sirket", "Sirket")
                        .WithMany("Ceks")
                        .HasForeignKey("SirketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BankaHesap");

                    b.Navigation("CariHesap");

                    b.Navigation("Sirket");
                });

            modelBuilder.Entity("SantiyeOnMuh.Entity.Nakit", b =>
                {
                    b.HasOne("SantiyeOnMuh.Entity.BankaHesap", "BankaHesap")
                        .WithMany("Nakits")
                        .HasForeignKey("BankaHesapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SantiyeOnMuh.Entity.CariHesap", "CariHesap")
                        .WithMany("Nakits")
                        .HasForeignKey("CariHesapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SantiyeOnMuh.Entity.Sirket", "Sirket")
                        .WithMany("Nakits")
                        .HasForeignKey("SirketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BankaHesap");

                    b.Navigation("CariHesap");

                    b.Navigation("Sirket");
                });

            modelBuilder.Entity("SantiyeOnMuh.Entity.SantiyeKasa", b =>
                {
                    b.HasOne("SantiyeOnMuh.Entity.SantiyeGiderKalemi", "SantiyeGiderKalemi")
                        .WithMany("SantiyeKasas")
                        .HasForeignKey("SantiyeGiderKalemiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SantiyeOnMuh.Entity.Santiye", "Santiye")
                        .WithMany("SantiyeKasas")
                        .HasForeignKey("SantiyeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Santiye");

                    b.Navigation("SantiyeGiderKalemi");
                });

            modelBuilder.Entity("SantiyeOnMuh.Entity.BankaHesap", b =>
                {
                    b.Navigation("BankaKasas");

                    b.Navigation("Ceks");

                    b.Navigation("Nakits");
                });

            modelBuilder.Entity("SantiyeOnMuh.Entity.CariGiderKalemi", b =>
                {
                    b.Navigation("CariKasas");
                });

            modelBuilder.Entity("SantiyeOnMuh.Entity.CariHesap", b =>
                {
                    b.Navigation("CariKasas");

                    b.Navigation("Ceks");

                    b.Navigation("Nakits");
                });

            modelBuilder.Entity("SantiyeOnMuh.Entity.Santiye", b =>
                {
                    b.Navigation("CariHesaps");

                    b.Navigation("SantiyeKasas");
                });

            modelBuilder.Entity("SantiyeOnMuh.Entity.SantiyeGiderKalemi", b =>
                {
                    b.Navigation("SantiyeKasas");
                });

            modelBuilder.Entity("SantiyeOnMuh.Entity.Sirket", b =>
                {
                    b.Navigation("Ceks");

                    b.Navigation("Nakits");
                });
#pragma warning restore 612, 618
        }
    }
}
