// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SantiyeOnMuh.DataAccess.Concrete;

#nullable disable

namespace SantiyeOnMuh.DataAccess.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SantiyeOnMuh.Entity.EBankaHesap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BankaAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Durum")
                        .HasColumnType("bit");

                    b.Property<string>("HesapAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HesapNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IbanNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BankaHesaps");
                });

            modelBuilder.Entity("SantiyeOnMuh.Entity.EBankaKasa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BankaHesapId")
                        .HasColumnType("int");

                    b.Property<int?>("CekKaynak")
                        .HasColumnType("int");

                    b.Property<decimal>("Cikan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Durum")
                        .HasColumnType("bit");

                    b.Property<decimal>("Giren")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("NakitKaynak")
                        .HasColumnType("int");

                    b.Property<string>("Nitelik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SantiyeKasaKaynak")
                        .HasColumnType("int");

                    b.Property<DateTime>("SistemeGiris")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SonGuncelleme")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BankaHesapId");

                    b.ToTable("BankaKasas");
                });

            modelBuilder.Entity("SantiyeOnMuh.Entity.ECariGiderKalemi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Durum")
                        .HasColumnType("bit");

                    b.Property<bool>("Tur")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("CariGiderKalemis");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "ÇEK",
                            Durum = true,
                            Tur = false
                        },
                        new
                        {
                            Id = 2,
                            Ad = "NAKİT",
                            Durum = true,
                            Tur = false
                        });
                });

            modelBuilder.Entity("SantiyeOnMuh.Entity.ECariHesap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Adres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Durum")
                        .HasColumnType("bit");

                    b.Property<string>("IlgiliKisi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IlgiliKisiTelefon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Odeme")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SantiyeId")
                        .HasColumnType("int");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VergiNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SantiyeId");

                    b.ToTable("CariHesaps");
                });

            modelBuilder.Entity("SantiyeOnMuh.Entity.ECariKasa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Alacak")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BirimFiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Borc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CariGiderKalemiId")
                        .HasColumnType("int");

                    b.Property<int>("CariHesapId")
                        .HasColumnType("int");

                    b.Property<int?>("CekKaynak")
                        .HasColumnType("int");

                    b.Property<bool>("Durum")
                        .HasColumnType("bit");

                    b.Property<string>("ImgUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Miktar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("NakitKaynak")
                        .HasColumnType("int");

                    b.Property<DateTime>("SistemeGiris")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SonGuncelleme")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CariGiderKalemiId");

                    b.HasIndex("CariHesapId");

                    b.ToTable("CariKasas");
                });

            modelBuilder.Entity("SantiyeOnMuh.Entity.ECek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BankaHesapId")
                        .HasColumnType("int");

                    b.Property<int?>("BankaKasaKaynak")
                        .HasColumnType("int");

                    b.Property<int>("CariHesapId")
                        .HasColumnType("int");

                    b.Property<int?>("CariKasaKaynak")
                        .HasColumnType("int");

                    b.Property<string>("CekNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Durum")
                        .HasColumnType("bit");

                    b.Property<string>("ImgUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("OdemeDurumu")
                        .HasColumnType("bit");

                    b.Property<int>("SirketId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SistemeGiris")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SonGuncelleme")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BankaHesapId");

                    b.HasIndex("CariHesapId");

                    b.HasIndex("SirketId");

                    b.ToTable("Ceks");
                });

            modelBuilder.Entity("SantiyeOnMuh.Entity.ENakit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BankaHesapId")
                        .HasColumnType("int");

                    b.Property<int?>("BankaKasaKaynak")
                        .HasColumnType("int");

                    b.Property<int>("CariHesapId")
                        .HasColumnType("int");

                    b.Property<int?>("CariKasaKaynak")
                        .HasColumnType("int");

                    b.Property<bool>("Durum")
                        .HasColumnType("bit");

                    b.Property<string>("ImgUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SirketId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SistemeGiris")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SonGuncelleme")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BankaHesapId");

                    b.HasIndex("CariHesapId");

                    b.HasIndex("SirketId");

                    b.ToTable("Nakits");
                });

            modelBuilder.Entity("SantiyeOnMuh.Entity.ESantiye", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Adres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Durum")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Santiyes");
                });

            modelBuilder.Entity("SantiyeOnMuh.Entity.ESantiyeGiderKalemi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Durum")
                        .HasColumnType("bit");

                    b.Property<bool>("Tur")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("SantiyeGiderKalemis");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "ŞANTİYE KASASINA EFT",
                            Durum = true,
                            Tur = false
                        });
                });

            modelBuilder.Entity("SantiyeOnMuh.Entity.ESantiyeKasa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BankaKasaKaynak")
                        .HasColumnType("int");

                    b.Property<bool>("Durum")
                        .HasColumnType("bit");

                    b.Property<decimal>("Gelir")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Gider")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ImgUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kisi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("No")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SantiyeGiderKalemiId")
                        .HasColumnType("int");

                    b.Property<int>("SantiyeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SistemeGiris")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SonGuncelleme")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SantiyeGiderKalemiId");

                    b.HasIndex("SantiyeId");

                    b.ToTable("SantiyesKasas");
                });

            modelBuilder.Entity("SantiyeOnMuh.Entity.ESirket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Durum")
                        .HasColumnType("bit");

                    b.Property<string>("VergiNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sirkets");
                });

            modelBuilder.Entity("SantiyeOnMuh.Entity.EBankaKasa", b =>
                {
                    b.HasOne("SantiyeOnMuh.Entity.EBankaHesap", "BankaHesap")
                        .WithMany("BankaKasas")
                        .HasForeignKey("BankaHesapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BankaHesap");
                });

            modelBuilder.Entity("SantiyeOnMuh.Entity.ECariHesap", b =>
                {
                    b.HasOne("SantiyeOnMuh.Entity.ESantiye", "Santiye")
                        .WithMany("CariHesaps")
                        .HasForeignKey("SantiyeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Santiye");
                });

            modelBuilder.Entity("SantiyeOnMuh.Entity.ECariKasa", b =>
                {
                    b.HasOne("SantiyeOnMuh.Entity.ECariGiderKalemi", "CariGiderKalemi")
                        .WithMany("CariKasas")
                        .HasForeignKey("CariGiderKalemiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SantiyeOnMuh.Entity.ECariHesap", "CariHesap")
                        .WithMany("CariKasas")
                        .HasForeignKey("CariHesapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CariGiderKalemi");

                    b.Navigation("CariHesap");
                });

            modelBuilder.Entity("SantiyeOnMuh.Entity.ECek", b =>
                {
                    b.HasOne("SantiyeOnMuh.Entity.EBankaHesap", "BankaHesap")
                        .WithMany("Ceks")
                        .HasForeignKey("BankaHesapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SantiyeOnMuh.Entity.ECariHesap", "CariHesap")
                        .WithMany("Ceks")
                        .HasForeignKey("CariHesapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SantiyeOnMuh.Entity.ESirket", "Sirket")
                        .WithMany("Ceks")
                        .HasForeignKey("SirketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BankaHesap");

                    b.Navigation("CariHesap");

                    b.Navigation("Sirket");
                });

            modelBuilder.Entity("SantiyeOnMuh.Entity.ENakit", b =>
                {
                    b.HasOne("SantiyeOnMuh.Entity.EBankaHesap", "BankaHesap")
                        .WithMany("Nakits")
                        .HasForeignKey("BankaHesapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SantiyeOnMuh.Entity.ECariHesap", "CariHesap")
                        .WithMany("Nakits")
                        .HasForeignKey("CariHesapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SantiyeOnMuh.Entity.ESirket", "Sirket")
                        .WithMany("Nakits")
                        .HasForeignKey("SirketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BankaHesap");

                    b.Navigation("CariHesap");

                    b.Navigation("Sirket");
                });

            modelBuilder.Entity("SantiyeOnMuh.Entity.ESantiyeKasa", b =>
                {
                    b.HasOne("SantiyeOnMuh.Entity.ESantiyeGiderKalemi", "SantiyeGiderKalemi")
                        .WithMany("SantiyeKasas")
                        .HasForeignKey("SantiyeGiderKalemiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SantiyeOnMuh.Entity.ESantiye", "Santiye")
                        .WithMany("SantiyeKasas")
                        .HasForeignKey("SantiyeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Santiye");

                    b.Navigation("SantiyeGiderKalemi");
                });

            modelBuilder.Entity("SantiyeOnMuh.Entity.EBankaHesap", b =>
                {
                    b.Navigation("BankaKasas");

                    b.Navigation("Ceks");

                    b.Navigation("Nakits");
                });

            modelBuilder.Entity("SantiyeOnMuh.Entity.ECariGiderKalemi", b =>
                {
                    b.Navigation("CariKasas");
                });

            modelBuilder.Entity("SantiyeOnMuh.Entity.ECariHesap", b =>
                {
                    b.Navigation("CariKasas");

                    b.Navigation("Ceks");

                    b.Navigation("Nakits");
                });

            modelBuilder.Entity("SantiyeOnMuh.Entity.ESantiye", b =>
                {
                    b.Navigation("CariHesaps");

                    b.Navigation("SantiyeKasas");
                });

            modelBuilder.Entity("SantiyeOnMuh.Entity.ESantiyeGiderKalemi", b =>
                {
                    b.Navigation("SantiyeKasas");
                });

            modelBuilder.Entity("SantiyeOnMuh.Entity.ESirket", b =>
                {
                    b.Navigation("Ceks");

                    b.Navigation("Nakits");
                });
#pragma warning restore 612, 618
        }
    }
}
